from google import genai
from dotenv import load_dotenv
import os

load_dotenv()

client = genai.Client(api_key=os.getenv('GENAI_KEY'))

def summarize(transcript_text, subject, degree, semester=0):

    prompt = f'You are college lecture summarizer. You will be taking the transcript text and summarizing the entire text and providing the important summary in points within 250 words. The subject that the teacher is teaching is {subject} and the students are of {degree}. Remeber to give the summary according to the subject provided. Also make sure that your output doesnot contain anything that tells that this summary is generated by AI. Please provide the summary of the text given here: {transcript_text}'
    response = client.models.generate_content(
        model="gemini-2.0-flash", contents=prompt
    )
    return response.text
